<?php
function fakeDbQuery($offset = 0, $limit = 12) {
  $orgs_array = array(
      array(
          "region"=> "East Asia & Pacific",
          "country"=> "New Zealand",
          "country_income_level"=> "High income",
          "organization_name"=> "200 Square",
          "organization_type"=> "For-profit",
          "sectors"=> "Housing, construction & real estate",
          "description"=> "200 Square is an online real estate agent in New Zealand.",
          "city"=> "Wellington",
          "state_or_region"=> "Wellington",
          "founding_year"=> 2010,
          "size"=> "1 to 10",
          "type_of_data_used"=> "Housing, Education",
          "profile_id"=> "731"
      ),
      array(
          "region"=> "Europe & Central Asia",
          "country"=> "United Kingdom",
          "country_income_level"=> "High income",
          "organization_name"=> "21c Consultancy",
          "organization_type"=> "For-profit",
          "sectors"=> "IT and geospatial",
          "description"=> "21c is ICT innovation consultancy which advises international actors, institutions and governments around the world on technological trends which can affect the way they deliver services.",
          "city"=> "London",
          "state_or_region"=> "",
          "founding_year"=> 2015,
          "size"=> "1 to 10",
          "type_of_data_used"=> "",
          "profile_id"=> "1694"
        ),
        array(
          "region"=> "Europe & Central Asia",
          "country"=> "Russian Federation",
          "country_income_level"=> "High income",
          "organization_name"=> "2GIS",
          "organization_type"=> "For-profit",
          "sectors"=> "IT and geospatial",
          "description"=> "2GIS is a city information service combined with a map. ",
          "city"=> "Novosibirsk",
          "state_or_region"=> "Novosibirsk Oblast",
          "founding_year"=> 1999,
          "size"=> "1000+",
          "type_of_data_used"=> "Transportation, Geospatial, Business",
          "profile_id"=> "1025"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "2nd city Zoning",
          "organization_type"=> "Nonprofit",
          "sectors"=> "Housing, construction & real estate",
          "description"=> "An Open city App, 2nd city Zoning is an interactive map that lets you find out how your building is zoned, learn where to locate your business and explore zoning patterns throughout the city.",
          "city"=> "Chicago",
          "state_or_region"=> "Illinois",
          "founding_year"=> 2013,
          "size"=> "1 to 10",
          "type_of_data_used"=> "Housing",
          "profile_id"=> "1693"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "3 Round Stones Inc",
          "organization_type"=> "For-profit",
          "sectors"=> "IT and geospatial",
          "description"=> "3 Round Stones' Open Source platform is used by the Fortune 2000 and US Government Agencies to collect, publish and reuse data, both public and proprietary.",
          "city"=> "Arlington",
          "state_or_region"=> "Virginia",
          "founding_year"=> 2010,
          "size"=> "1 to 10",
          "type_of_data_used"=> "Weather, Science and research, Health/healthcare, Geospatial, Environment, Energy, Demographic and social, Business",
          "profile_id"=> "580"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "360 Yield Center",
          "organization_type"=> "For-profit",
          "sectors"=> "Agriculture",
          "description"=> "Taking a 360-degree view of key yield-limiting variables, 360 Yield Center develops strategies for better-performing crops and better on-farm profits.",
          "city"=> "Morton",
          "state_or_region"=> "Illinois",
          "founding_year"=> 2014,
          "size"=> "51 to 200",
          "type_of_data_used"=> "Agriculture, Environment, Weather",
          "profile_id"=> "1692"
        ),
        array(
          "region"=> "Europe & Central Asia",
          "country"=> "Denmark",
          "country_income_level"=> "High income",
          "organization_name"=> "3Strikes - city Stories",
          "organization_type"=> "For-profit",
          "sectors"=> "Arts, culture and tourism",
          "description"=> "city Stories provides a platform that allows users to explore local stories and simultaneously contribute their own.",
          "city"=> "Aarhus",
          "state_or_region"=> "Central Denmark region",
          "founding_year"=> 2015,
          "size"=> "1 to 10",
          "type_of_data_used"=> "Arts and culture",
          "profile_id"=> "2278"
        ),
        array(
          "region"=> "Europe & Central Asia",
          "country"=> "Finland",
          "country_income_level"=> "High income",
          "organization_name"=> "3Tier (Europe) ",
          "organization_type"=> "For-profit",
          "sectors"=> "Energy and climate",
          "description"=> "3TIER is a global environmental and industrial measurement company providing weather-driven renewable energy risk assessment and forecasting for wind, solar, and hydro power projects.",
          "city"=> "Helsinki",
          "state_or_region"=> "Uusimaa",
          "founding_year"=> 2012,
          "size"=> "11 to 50",
          "type_of_data_used"=> "Other, Environment",
          "profile_id"=> "952"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "5PSolutions",
          "organization_type"=> "For-profit",
          "sectors"=> "IT and geospatial",
          "description"=> "5PSolutions are artisans of mobile platforms.",
          "city"=> "Fairfax",
          "state_or_region"=> "Virginia",
          "founding_year"=> 2007,
          "size"=> "1 to 10",
          "type_of_data_used"=> "Environment",
          "profile_id"=> "534"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "AAA National",
          "organization_type"=> "Other",
          "sectors"=> "Transportation and logistics",
          "description"=> "AAA provides services such as travel, automotive, insurance, financial, and discounts.",
          "city"=> "Irving",
          "state_or_region"=> "Texas",
          "founding_year"=> 1902,
          "size"=> "201 to 1000",
          "type_of_data_used"=> "Transportation",
          "profile_id"=> "1691"
        ),
        array(
          "region"=> "North America",
          "country"=> "United States",
          "country_income_level"=> "High income",
          "organization_name"=> "AAASHTO",
          "organization_type"=> "Other",
          "sectors"=> "Transportation and logistics",
          "description"=> "AASHTO works to educate the public and key decision makers about the critical role that transportation plays in securing a good quality of life and sound economy. AASHTO serves as a liaison between state departments of transportation and the Federal government.",
          "city"=> "Washington",
          "state_or_region"=> "DC",
          "founding_year"=> 1913,
          "size"=> "51 to 200",
          "type_of_data_used"=> "Transportation",
          "profile_id"=> "1690"
        ),
        array(
          "region"=> "Latin America & Caribbean",
          "country"=> "Chile",
          "country_income_level"=> "High income",
          "organization_name"=> "ABRELATAM",
          "organization_type"=> "Nonprofit",
          "sectors"=> "Governance",
          "description"=> "ABRELATAM is an conference that seeks to accelerate the process of opening information through Open Data transparency and promote the Latin America.",
          "city"=> "Santiago",
          "state_or_region"=> "",
          "founding_year"=> 2015,
          "size"=> "",
          "type_of_data_used"=> "",
          "profile_id"=> "1687"
        )
   );
   return array_slice($orgs_array, $offset, $limit);
}
 ?>
